# Generated by Django 4.2.1 on 2026-08-16 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgainWomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ИменаНоНеймов')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='СЛагъ')),
            ],
            options={
                'verbose_name': 'Категорька из категорий в классе Мета',
                'verbose_name_plural': 'Категорьки из категорий в классе Мета',
            },
        ),
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('some_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sitewomen/uploads_model')),
            ],
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='зугаловах')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='СЛагъ')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='media/%Y/%m/%d', verbose_name='Фотка🔳')),
                ('content', models.TextField(blank=True, verbose_name='КАНТЕНТсодержимое')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Тайм рождения')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обнова')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Стутус')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='women.category', verbose_name='Котигория')),
                ('husband', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wuman', to='women.husband', verbose_name='Мужьяки')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='women.tagpost', verbose_name='Тегишки')),
            ],
            options={
                'verbose_name': 'Женщина с планеты кибертрон в классе мета',
                'verbose_name_plural': 'Женщины с планеты кибертрон в классе мета',
                'ordering': ['time_create'],
                'indexes': [models.Index(fields=['time_create'], name='women_women_time_cr_21b781_idx')],
            },
        ),
    ]
