# Generated by Django 4.2.1 on 2026-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', 'copy_0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgainWomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
