# Generated by Django 4.2.1 on 2026-07-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_women_managers_alter_women_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='women',
            managers=[
            ],
        ),
    ]
