# Generated by Django 4.2.1 on 2026-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_tagpost_alter_women_cat_women_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='women.tagpost'),
        ),
    ]
